local GlobalApi = require("Global/GlobalApi")
local MathLib   = require("util/MathLib")

local DATA      = {
  ["default"] = {
    MIN_VALUE  = 0,
    MAX_VALUE  = 99,
    POSITION   = "0 5 -6",
    ROTATION   = "0 0 180",
    HEIGHT     = 650,
    WIDTH      = 1000,
    FONT_SIZE  = 400,
    FONT_COLOR = "#FFFFFF"
  },
  ["damage"] = {
    ROTATION = "0 180 180",
    POSITION = "-7 5 6",
    MESSAGE  = true
  },
  ["horror"] = {
    POSITION = "5 -15 6",
    ROTATION = "0 180 180",
    MESSAGE  = true
  },
  ["resourceCounter"] = {
    MESSAGE  = true
  },
  ["clueCounter"] = {
    MESSAGE = true
  },
  ["DoomCounter"] = {
    SIZE       = 800,
    FONT_SIZE  = 650,
    FONT_COLOR = "#FFFFFFF2",
  }
}

function onDestroy()
  updateSave()
end

function updateSave()
  self.script_state = val
end

function getDataValue(key)
  local data = DATA[self.getMemo()] or DATA["default"]
  return data[key] or DATA["default"][key]
end

function onLoad(savedData)
  val = tonumber(savedData) or 0
  self.max_typed_number = getDataValue("MAX_VALUE")

  createXml()

  -- add context menu entries
  self.addContextMenuItem("Add 5", function() modifyValue(5, true) end)
  self.addContextMenuItem("Subtract 5", function() modifyValue(-5, true) end)
  self.addContextMenuItem("Add 10", function() modifyValue(10, true) end)
  self.addContextMenuItem("Subtract 10", function() modifyValue(-10, true) end)
end

function createXml()

  local xml = {
    {
      tag = "Button",
      attributes = {
        id            = "xmlBtn",
        image         = "circle",
        onClick       = "addOrSubtract",
        scale         = "0.35 0.35 1",
        rayCastTarget = true,
        colors        = getColorBlock("#00000000"),
        position      = getDataValue("POSITION"),
        rotation      = getDataValue("ROTATION"),
        height        = getDataValue("HEIGHT"),
        width         = getDataValue("WIDTH"),
      },
      children = {
        {
          tag = "Text",
          attributes = {
            id        = "xmlTxt",
            fontSize  = getFontSize(val),
            font      = "font_arkham-numbers",
            text      = val,
            color = getDataValue("FONT_COLOR")
          }
        }
      }
    }
  }
  self.UI.setXmlTable(xml)
end

function getColorBlock(hexColor)
  return table.concat({ hexColor, hexColor, hexColor }, "|")
end

function onNumberTyped(_, number)
  updateVal(number, true)
end

function addOrSubtract(_, clickType)
  local mod = 1
  if clickType == "-2" then
    mod = -1
  end
  modifyValue(mod, true)
end

function getFontSize(val)
  local fontSize = getDataValue("FONT_SIZE")
  if val > 99 then return fontSize * 0.81 end
  if val > 9 then return fontSize * 0.9 end
  return fontSize
end

function updateVal(newVal, logChange)
  if not tonumber(newVal) then return end
  newVal = MathLib.clamp(newVal, getDataValue("MIN_VALUE"), getDataValue("MAX_VALUE"))
  actualUpdate(newVal, logChange)
end

function actualUpdate(newVal, logChange)
  -- register for message
  if getDataValue("MESSAGE") and logChange then
    GlobalApi.sendManualCounterChange(self, newVal - val)
  end

  -- perform the variable and label update
  val = newVal
  self.UI.setAttribute("xmlTxt", "fontSize", getFontSize(val))
  self.UI.setAttribute("xmlTxt", "text", val)
  updateSave()
end

function modifyValue(mod, logChange)
  local newVal = MathLib.clamp(val + tonumber(mod), getDataValue("MIN_VALUE"), getDataValue("MAX_VALUE"))
  actualUpdate(newVal, logChange)
end
