do
  local CHAOS_TOKEN_NAMES = {
    ["Elder Sign"] = true,
    ["+1"] = true,
    ["0"] = true,
    ["-1"] = true,
    ["-2"] = true,
    ["-3"] = true,
    ["-4"] = true,
    ["-5"] = true,
    ["-6"] = true,
    ["-7"] = true,
    ["-8"] = true,
    ["Skull"] = true,
    ["Cultist"] = true,
    ["Tablet"] = true,
    ["Elder Thing"] = true,
    ["Auto-fail"] = true,
    ["Bless"] = true,
    ["Curse"] = true,
    ["Frost"] = true,
    ["Blood"] = true
  }

  local TokenChecker = {}

  -- returns true if the passed object is a chaos token (by name)
  function TokenChecker.isChaosToken(obj)
    return obj.type == "Tile" and CHAOS_TOKEN_NAMES[obj.getName()]
  end

  -- returns true if the passed name is a chaos token name
  function TokenChecker.isChaosTokenName(objName)
    return CHAOS_TOKEN_NAMES[objName]
  end

  return TokenChecker
end
